# Generated by Django 3.1 on 2023-04-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('terminal_image', models.ImageField(blank=True, upload_to='photos/terminals')),
                ('kwatt', models.CharField(max_length=50, unique=True)),
                ('connector', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, choices=[('disponible', 'disponible'), ('Indisponible', 'Indisponible'), ('En panne', 'En Panne')], max_length=50)),
                ('price', models.IntegerField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
